- hosts: localhost
  connection: local

  vars:
    homedir: "{{ lookup('env','HOME') }}" 
    builddir: "{{ homedir }}/.build"
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ homedir }}/.ssh/id_ed25519"

  pre_tasks:
  - name: do a "pacman -Syu"
    community.general.pacman:
      update_cache: true
      upgrade: true

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/base-packages.yml
    - include_tasks: tasks/yay.yml
    - include_tasks: tasks/yay-packages.yml
    - include_tasks: tasks/zshenv.yml
    - include_tasks: tasks/zap.yml
    - include_tasks: tasks/dotfiles.yml
