---
- hosts: localhost
  connection: local

  vars:
    homedir: "{{ lookup('env','HOME') }}" 
    builddir: "{{ homedir }}/.build"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ homedir }}/.ssh/id_rsa"

  pre_tasks:
  - name: Update pacman cache and perform a system upgrade
    become: true
    community.general.pacman:
      update_cache: true
      upgrade: true

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/pacman-setup.yml
    - include_tasks: tasks/base-packages.yml
    - include_tasks: tasks/npm.yml
    - include_tasks: tasks/yay.yml
    - include_tasks: tasks/aur-packages.yml
    - include_tasks: tasks/ly-setup.yml
    - include_tasks: tasks/zshenv.yml
    - include_tasks: tasks/zap.yml
    - include_tasks: tasks/dotfiles.yml
