- name: Install AUR packages
  community.general.pacman:
    name:
      - nekoray-bin
      - visual-studio-code-bin
      - ly
    state: present
    executable: yay
    extra_args: --builddir "{{ homedir }}/.cache/yay"
