- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Download wlfft.aur module
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py
    dest: "{{ homedir }}/.ansible/plugins/modules/aur.py"

- name: Installing AUR packages
  become_user: aur_builder
  aur:
    use: yay
    name:
      - nekoray-bin
      - visual-studio-code-bin
      - ly
